/*
 * This file was automatically generated, do not edit.
 */

#include <geogram/bibliography/bibliography.h>

void register_embedded_bib_file(void);
   
void register_embedded_bib_file() {
     GEO::Biblio::register_references(
        " \n"
        "@misc{WEB:GEOGRAM, \n"
        "  title = {Geogram: a programming library of geometric algorithms}, \n"
        "  author = {Inria, project ALICE-GRAPHYS}, \n"
        "  howpublished = {\\url{http://alice.loria.fr/software/geogram/doc/html/index.html}} \n"
        "} \n"
        " \n"
        "@article{journals/CAD/CatmullRGB, \n"
        "  title = \"Recursively generated B-spline surfaces on arbitrary topological meshes\", \n"
        "  journal = \"Computer-Aided Design\", \n"
        "  volume = \"10\", \n"
        "  number = \"6\", \n"
        "  pages = \"350 - 355\", \n"
        "  year = \"1978\", \n"
        "  note = \"\", \n"
        "  issn = \"0010-4485\", \n"
        "  doi = \"http://dx.doi.org/10.1016/0010-4485(78)90110-0\", \n"
        "  url = \"http://www.sciencedirect.com/science/article/pii/0010448578901100\", \n"
        "  author = \"E. Catmull and J. Clark\", \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/EdelsbrunnerM90, \n"
        "  author    = {Herbert Edelsbrunner and \n"
        "               Ernst P. M{\\\"{u}}cke}, \n"
        "  title     = {Simulation of simplicity: a technique to cope with degenerate cases \n"
        "               in geometric algorithms}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {9}, \n"
        "  number    = {1}, \n"
        "  pages     = {66--104}, \n"
        "  year      = {1990}, \n"
        "  url       = {http://doi.acm.org/10.1145/77635.77639}, \n"
        "  doi       = {10.1145/77635.77639}, \n"
        "  timestamp = {Tue, 25 Nov 2003 07:57:25 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/EdelsbrunnerM90}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/compgeom/Shewchuk96, \n"
        "  author    = {Jonathan Richard Shewchuk}, \n"
        "  title     = {Robust Adaptive Floating-Point Geometric Predicates}, \n"
        "  booktitle = {Proceedings of the Twelfth Annual Symposium on Computational Geometry, \n"
        "               Philadelphia, PA, USA, May 24-26, 1996}, \n"
        "  pages     = {141--150}, \n"
        "  year      = {1996}, \n"
        "  url       = {http://doi.acm.org/10.1145/237218.237337}, \n"
        "  doi       = {10.1145/237218.237337}, \n"
        "  timestamp = {Fri, 12 Jun 2015 15:27:08 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/compgeom/Shewchuk96}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{meyer:inria-00344297, \n"
        "  TITLE = {{FPG: A code generator for fast and certified geometric predicates}}, \n"
        "  AUTHOR = {Meyer, Andreas and Pion, Sylvain}, \n"
        "  URL = {https://hal.inria.fr/inria-00344297}, \n"
        "  BOOKTITLE = {{Real Numbers and Computers}}, \n"
        "  ADDRESS = {Santiago de Compostela, Spain}, \n"
        "  PAGES = {47-60}, \n"
        "  YEAR = {2008}, \n"
        "  MONTH = Jun, \n"
        "  PDF = {https://hal.inria.fr/inria-00344297/file/FPG_RNC8.pdf}, \n"
        "  HAL_ID = {inria-00344297}, \n"
        "  HAL_VERSION = {v1}, \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/toms/Si15, \n"
        "  author    = {Hang Si}, \n"
        "  title     = {TetGen, a Delaunay-Based Quality Tetrahedral Mesh Generator}, \n"
        "  journal   = {{ACM} Trans. Math. Softw.}, \n"
        "  volume    = {41}, \n"
        "  number    = {2}, \n"
        "  pages     = {11:1--11:36}, \n"
        "  year      = {2015}, \n"
        "  url       = {http://doi.acm.org/10.1145/2629697}, \n"
        "  doi       = {10.1145/2629697}, \n"
        "  timestamp = {Mon, 20 Apr 2015 18:26:51 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/toms/Si15}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/wacg/Shewchuk96, \n"
        "  author    = {Jonathan Richard Shewchuk}, \n"
        "  title     = {Triangle: Engineering a 2D Quality Mesh Generator and Delaunay Triangulator}, \n"
        "  booktitle = {Applied Computational Geormetry, Towards Geometric Engineering, FCRC'96 \n"
        "               Workshop, WACG'96, Philadelphia, PA, May 27-28, 1996, Selected Papers}, \n"
        "  pages     = {203--222}, \n"
        "  year      = {1996}, \n"
        "  url       = {http://dx.doi.org/10.1007/BFb0014497}, \n"
        "  doi       = {10.1007/BFb0014497}, \n"
        "  timestamp = {Mon, 27 Jun 2011 15:25:52 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/wacg/Shewchuk96}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/KazhdanH13, \n"
        "  author    = {Michael M. Kazhdan and \n"
        "               Hugues Hoppe}, \n"
        "  title     = {Screened poisson surface reconstruction}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {32}, \n"
        "  number    = {3}, \n"
        "  pages     = {29:1--29:13}, \n"
        "  year      = {2013}, \n"
        "  url       = {http://doi.acm.org/10.1145/2487228.2487237}, \n"
        "  doi       = {10.1145/2487228.2487237}, \n"
        "  timestamp = {Tue, 03 Jan 2017 12:35:33 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/KazhdanH13}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/comgeo/BoissonnatDPTY02, \n"
        "  author    = {Jean{-}Daniel Boissonnat and \n"
        "               Olivier Devillers and \n"
        "               Sylvain Pion and \n"
        "               Monique Teillaud and \n"
        "               Mariette Yvinec}, \n"
        "  title     = {Triangulations in {CGAL}}, \n"
        "  journal   = {Comput. Geom.}, \n"
        "  volume    = {22}, \n"
        "  number    = {1-3}, \n"
        "  pages     = {5--19}, \n"
        "  year      = {2002}, \n"
        "  url       = {http://dx.doi.org/10.1016/S0925-7721(01)00054-2}, \n"
        "  doi       = {10.1016/S0925-7721(01)00054-2}, \n"
        "  timestamp = {Mon, 04 Jul 2011 15:42:34 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/comgeo/BoissonnatDPTY02}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/imr/Si06, \n"
        "  author    = {Hang Si}, \n"
        "  title     = {On Refinement of Constrained Delaunay Tetrahedralizations}, \n"
        "  booktitle = {Proceedings of the 15th International Meshing Roundtable, Birmingham, \n"
        "               Alabama, USA, September 17-20, 2006, Proceedings}, \n"
        "  pages     = {509--528}, \n"
        "  year      = {2006}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-540-34958-7_29}, \n"
        "  doi       = {10.1007/978-3-540-34958-7_29}, \n"
        "  timestamp = {Tue, 16 Jun 2015 19:31:31 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/imr/Si06}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cj/Bowyer81, \n"
        "  author    = {Adrian Bowyer}, \n"
        "  title     = {Computing Dirichlet Tessellations}, \n"
        "  journal   = {Comput. J.}, \n"
        "  volume    = {24}, \n"
        "  number    = {2}, \n"
        "  pages     = {162--166}, \n"
        "  year      = {1981}, \n"
        "  url       = {http://dx.doi.org/10.1093/comjnl/24.2.162}, \n"
        "  doi       = {10.1093/comjnl/24.2.162}, \n"
        "  timestamp = {Tue, 28 Jun 2011 15:15:23 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cj/Bowyer81}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{journals/cj/Watson81, \n"
        "  author    = {David Watson}, \n"
        "  title     = {Computing the n-dimensional Delaunay tessellation with application to Voronoi polytopes}, \n"
        "  journal   = {Comput. J.}, \n"
        "  volume    = {24}, \n"
        "  number    = {2}, \n"
        "  pages     = {167--172}, \n"
        "  year      = {1981} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/compgeom/AmentaCR03, \n"
        "  author    = {Nina Amenta and \n"
        "               Sunghee Choi and \n"
        "               G{\\\"{u}}nter Rote}, \n"
        "  title     = {Incremental constructions con {BRIO}}, \n"
        "  booktitle = {Proceedings of the 19th {ACM} Symposium on Computational Geometry, \n"
        "               San Diego, CA, USA, June 8-10, 2003}, \n"
        "  pages     = {211--219}, \n"
        "  year      = {2003}, \n"
        "  url       = {http://doi.acm.org/10.1145/777792.777824}, \n"
        "  doi       = {10.1145/777792.777824}, \n"
        "  timestamp = {Fri, 30 Jan 2015 14:53:39 +0100}, \n"
        "  biburl    = {http://dblp2.uni-trier.de/rec/bib/conf/compgeom/AmentaCR03}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/ijfcs/DevillersPT02, \n"
        "  author    = {Olivier Devillers and \n"
        "               Sylvain Pion and \n"
        "               Monique Teillaud}, \n"
        "  title     = {Walking in a Triangulation}, \n"
        "  journal   = {Int. J. Found. Comput. Sci.}, \n"
        "  volume    = {13}, \n"
        "  number    = {2}, \n"
        "  pages     = {181--199}, \n"
        "  year      = {2002}, \n"
        "  url       = {http://dx.doi.org/10.1142/S0129054102001047}, \n"
        "  doi       = {10.1142/S0129054102001047}, \n"
        "  timestamp = {Fri, 14 Sep 2012 10:05:51 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/ijfcs/DevillersPT02}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@misc{WEB:SpatialSorting, \n"
        "  title = {Spatial Sorting}, \n"
        "  author = {Christophe Delage and Olivier Devillers}, \n"
        "  howpublished = {\\url{http://doc.cgal.org/latest/Spatial_sorting/index.html}} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/comgeo/FunkeMN05, \n"
        "  author    = {Stefan Funke and \n"
        "               Kurt Mehlhorn and \n"
        "               Stefan N{\\\"{a}}her}, \n"
        "  title     = {Structural filtering: a paradigm for efficient and exact geometric \n"
        "               programs}, \n"
        "  journal   = {Comput. Geom.}, \n"
        "  volume    = {31}, \n"
        "  number    = {3}, \n"
        "  pages     = {179--194}, \n"
        "  year      = {2005}, \n"
        "  url       = {http://dx.doi.org/10.1016/j.comgeo.2004.12.007}, \n"
        "  doi       = {10.1016/j.comgeo.2004.12.007}, \n"
        "  timestamp = {Tue, 08 Nov 2005 10:35:40 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/comgeo/FunkeMN05}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@misc{WEB:ImGUI, \n"
        "  title = {{ImGUI}: bloat free immediate mode GUI}, \n"
        "  author = {Omar Cornut}, \n"
        "  howpublished = {\\url{https://github.com/ocornut/imgui}} \n"
        "} \n"
        " \n"
        "@misc{WEB:HLBFGS, \n"
        "  title = {{HLBFGS}: a hybrid {L-BFGS} optimization framework}, \n"
        "  author = {Yang Liu}, \n"
        "  howpublished = {\\url{https://sourceforge.net/u/hlbfgs/}} \n"
        "} \n"
        " \n"
        "@misc{WEB:libMeshb, \n"
        "  title = {{libMeshb}: a library to handle the meshb format}, \n"
        "  author = {Loic Marechal}, \n"
        "  howpublished = {\\url{https://github.com/LoicMarechal/libMeshb}} \n"
        "} \n"
        " \n"
        "@misc{WEB:rply, \n"
        "  title = {{ANSI} {C} Library for {PLY} file format input and output}, \n"
        "  author = {Diego Nehab}, \n"
        "  howpublished = {\\url{http://w3.impa.br/~diego/software/rply/}} \n"
        "} \n"
        " \n"
        "@misc{WEB:lua, \n"
        "  title = {the {L}ua programming language}, \n"
        "  author = {PUC-Rio}, \n"
        "  howpublished = {\\url{https://www.lua.org/}} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/LevyPRM02, \n"
        "  author    = {Bruno L{\\'{e}}vy and \n"
        "               Sylvain Petitjean and \n"
        "               Nicolas Ray and \n"
        "               J{\\'{e}}r{\\^{o}}me Maillot}, \n"
        "  title     = {Least squares conformal maps for automatic texture atlas generation}, \n"
        "  journal   = {{ACM} Trans. Graph., SIGGRAPH conf. proc.}, \n"
        "  volume    = {21}, \n"
        "  number    = {3}, \n"
        "  pages     = {362--371}, \n"
        "  year      = {2002}, \n"
        "  url       = {http://doi.acm.org/10.1145/566654.566590}, \n"
        "  doi       = {10.1145/566654.566590}, \n"
        "  timestamp = {Tue, 25 Nov 2003 07:57:27 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/LevyPRM02}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cgf/MullenTAD08, \n"
        "  author    = {Patrick Mullen and \n"
        "               Yiying Tong and \n"
        "               Pierre Alliez and \n"
        "               Mathieu Desbrun}, \n"
        "  title     = {Spectral Conformal Parameterization}, \n"
        "  journal   = {Comput. Graph. Forum}, \n"
        "  volume    = {27}, \n"
        "  number    = {5}, \n"
        "  pages     = {1487--1494}, \n"
        "  year      = {2008}, \n"
        "  url       = {http://dx.doi.org/10.1111/j.1467-8659.2008.01289.x}, \n"
        "  doi       = {10.1111/j.1467-8659.2008.01289.x}, \n"
        "  timestamp = {Tue, 28 Oct 2008 08:58:09 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cgf/MullenTAD08}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/ShefferLMB05, \n"
        "  author    = {Alla Sheffer and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Maxim Mogilnitsky and \n"
        "               Alexander Bogomyakov}, \n"
        "  title     = {{ABF++:} fast and robust angle based flattening}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {24}, \n"
        "  number    = {2}, \n"
        "  pages     = {311--330}, \n"
        "  year      = {2005}, \n"
        "  url       = {http://doi.acm.org/10.1145/1061347.1061354}, \n"
        "  doi       = {10.1145/1061347.1061354}, \n"
        "  timestamp = {Thu, 09 Feb 2006 13:53:54 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/ShefferLMB05}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/smi/Levy06, \n"
        "  author    = {Bruno L{\\'{e}}vy}, \n"
        "  title     = {Laplace-Beltrami Eigenfunctions Towards an Algorithm That \"Understands\" \n"
        "               Geometry}, \n"
        "  booktitle = {2006 International Conference on Shape Modeling and Applications {(SMI} \n"
        "               2006), 14-16 June 2006, Matsushima, Japan}, \n"
        "  pages     = {13}, \n"
        "  year      = {2006}, \n"
        "  url       = {http://dx.doi.org/10.1109/SMI.2006.21}, \n"
        "  doi       = {10.1109/SMI.2006.21}, \n"
        "  timestamp = {Fri, 01 Apr 2016 12:26:50 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/smi/Levy06}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/isvc/ToledoLP07, \n"
        "  author    = {Rodrigo de Toledo and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Jean{-}Claude Paul}, \n"
        "  title     = {Iterative Methods for Visualization of Implicit Surfaces On {GPU}}, \n"
        "  booktitle = {Advances in Visual Computing, Third International Symposium, {ISVC} \n"
        "               2007, Lake Tahoe, NV, USA, November 26-28, 2007, Proceedings, Part \n"
        "               {I}}, \n"
        "  pages     = {598--609}, \n"
        "  year      = {2007}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-540-76858-6_58}, \n"
        "  doi       = {10.1007/978-3-540-76858-6_58}, \n"
        "  timestamp = {Fri, 23 Nov 2007 14:22:57 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/isvc/ToledoLP07}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cgf/ValletL08, \n"
        "  author    = {Bruno Vallet and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Spectral Geometry Processing with Manifold Harmonics}, \n"
        "  journal   = {Comput. Graph. Forum}, \n"
        "  volume    = {27}, \n"
        "  number    = {2}, \n"
        "  pages     = {251--260}, \n"
        "  year      = {2008}, \n"
        "  url       = {http://dx.doi.org/10.1111/j.1467-8659.2008.01122.x}, \n"
        "  doi       = {10.1111/j.1467-8659.2008.01122.x}, \n"
        "  timestamp = {Thu, 18 Sep 2008 08:03:52 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cgf/ValletL08}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/RayLLSA06, \n"
        "  author    = {Nicolas Ray and \n"
        "               Wan{-}Chiu Li and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Alla Sheffer and \n"
        "               Pierre Alliez}, \n"
        "  title     = {Periodic global parameterization}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {25}, \n"
        "  number    = {4}, \n"
        "  pages     = {1460--1485}, \n"
        "  year      = {2006}, \n"
        "  url       = {http://doi.acm.org/10.1145/1183287.1183297}, \n"
        "  doi       = {10.1145/1183287.1183297}, \n"
        "  timestamp = {Tue, 06 Mar 2007 12:40:16 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/RayLLSA06}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/RayVLL08, \n"
        "  author    = {Nicolas Ray and \n"
        "               Bruno Vallet and \n"
        "               Wan{-}Chiu Li and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {N-symmetry direction field design}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {27}, \n"
        "  number    = {2}, \n"
        "  pages     = {10:1--10:13}, \n"
        "  year      = {2008}, \n"
        "  url       = {http://doi.acm.org/10.1145/1356682.1356683}, \n"
        "  doi       = {10.1145/1356682.1356683}, \n"
        "  timestamp = {Wed, 04 Jan 2017 11:34:22 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/RayVLL08}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/paapp/BuatoisCL09, \n"
        "  author    = {Luc Buatois and \n"
        "               Guillaume Caumon and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Concurrent number cruncher: a {GPU} implementation of a general sparse \n"
        "               linear solver}, \n"
        "  journal   = {{IJPEDS}}, \n"
        "  volume    = {24}, \n"
        "  number    = {3}, \n"
        "  pages     = {205--223}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://dx.doi.org/10.1080/17445760802337010}, \n"
        "  doi       = {10.1080/17445760802337010}, \n"
        "  timestamp = {Tue, 09 Nov 2010 08:30:19 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/paapp/BuatoisCL09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/RayVAL09, \n"
        "  author    = {Nicolas Ray and \n"
        "               Bruno Vallet and \n"
        "               Laurent Alonso and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Geometry-aware direction field processing}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {29}, \n"
        "  number    = {1}, \n"
        "  pages     = {1:1--1:11}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://doi.acm.org/10.1145/1640443.1640444}, \n"
        "  doi       = {10.1145/1640443.1640444}, \n"
        "  timestamp = {Wed, 04 Jan 2017 12:25:12 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/RayVAL09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/LiuWLSYLY09, \n"
        "  author    = {Yang Liu and \n"
        "               Wenping Wang and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Feng Sun and \n"
        "               Dong{-}Ming Yan and \n"
        "               Lin Lu and \n"
        "               Chenglei Yang}, \n"
        "  title     = {On centroidal voronoi tessellation - energy smoothness and fast computation}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {28}, \n"
        "  number    = {4}, \n"
        "  pages     = {101:1--101:17}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://doi.acm.org/10.1145/1559755.1559758}, \n"
        "  doi       = {10.1145/1559755.1559758}, \n"
        "  timestamp = {Wed, 04 Jan 2017 11:50:25 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/LiuWLSYLY09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cgf/YanLLSW09, \n"
        "  author    = {Dong{-}Ming Yan and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Yang Liu and \n"
        "               Feng Sun and \n"
        "               Wenping Wang}, \n"
        "  title     = {Isotropic Remeshing with Fast and Exact Computation of Restricted \n"
        "               Voronoi Diagram}, \n"
        "  journal   = {Comput. Graph. Forum}, \n"
        "  volume    = {28}, \n"
        "  number    = {5}, \n"
        "  pages     = {1445--1454}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://dx.doi.org/10.1111/j.1467-8659.2009.01521.x}, \n"
        "  doi       = {10.1111/j.1467-8659.2009.01521.x}, \n"
        "  timestamp = {Tue, 09 Sep 2014 19:02:15 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cgf/YanLLSW09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/imr/LevyB12, \n"
        "  author    = {Bruno L{\\'{e}}vy and \n"
        "               Nicolas Bonneel}, \n"
        "  title     = {Variational Anisotropic Surface Meshing with Voronoi Parallel Linear \n"
        "               Enumeration}, \n"
        "  booktitle = {Proceedings of the 21st International Meshing Roundtable, {IMR} 2012, \n"
        "               October 7-10, 2012, San Jose, CA, {USA}}, \n"
        "  pages     = {349--366}, \n"
        "  year      = {2012}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-642-33573-0_21}, \n"
        "  doi       = {10.1007/978-3-642-33573-0_21}, \n"
        "  timestamp = {Tue, 16 Jun 2015 19:31:31 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/imr/LevyB12}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/imr/NivoliersYL11, \n"
        "  author    = {Vincent Nivoliers and \n"
        "               Dong{-}Ming Yan and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Fitting Polynomial Surfaces to Triangular Meshes with Voronoi Squared \n"
        "               Distance Minimization}, \n"
        "  booktitle = {Proceedings of the 20th International Meshing Roundtable, {IMR} 2011, \n"
        "               October 23-26, 2011, Paris, France}, \n"
        "  pages     = {601--617}, \n"
        "  year      = {2011}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-642-24734-7_33}, \n"
        "  doi       = {10.1007/978-3-642-24734-7_33}, \n"
        "  timestamp = {Tue, 16 Jun 2015 19:31:33 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/imr/NivoliersYL11}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/ewc/NivoliersYL14, \n"
        "  author    = {Vincent Nivoliers and \n"
        "               Dong{-}Ming Yan and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Fitting polynomial surfaces to triangular meshes with Voronoi squared \n"
        "               distance minimization}, \n"
        "  journal   = {Eng. Comput. (Lond.)}, \n"
        "  volume    = {30}, \n"
        "  number    = {3}, \n"
        "  pages     = {289--300}, \n"
        "  year      = {2014}, \n"
        "  url       = {http://dx.doi.org/10.1007/s00366-012-0291-9}, \n"
        "  doi       = {10.1007/s00366-012-0291-9}, \n"
        "  timestamp = {Fri, 13 Jun 2014 11:31:20 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/ewc/NivoliersYL14}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        " \n"
        "@article{DBLP:journals/cgf/LuLW12, \n"
        "  author    = {Lin Lu and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Wenping Wang}, \n"
        "  title     = {Centroidal Voronoi Tessellation of Line Segments and Graphs}, \n"
        "  journal   = {Comput. Graph. Forum}, \n"
        "  volume    = {31}, \n"
        "  number    = {2}, \n"
        "  pages     = {775--784}, \n"
        "  year      = {2012}, \n"
        "  url       = {http://dx.doi.org/10.1111/j.1467-8659.2012.03058.x}, \n"
        "  doi       = {10.1111/j.1467-8659.2012.03058.x}, \n"
        "  timestamp = {Thu, 06 Sep 2012 16:52:43 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cgf/LuLW12}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/LevyL10, \n"
        "  author    = {Bruno L{\\'{e}}vy and \n"
        "               Yang Liu}, \n"
        "  title     = {\\emph{L}\\({}_{\\mbox{\\emph{p}}}\\) Centroidal Voronoi Tessellation and \n"
        "               its applications}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {29}, \n"
        "  number    = {4}, \n"
        "  pages     = {119:1--119:11}, \n"
        "  year      = {2010}, \n"
        "  url       = {http://doi.acm.org/10.1145/1833351.1778856}, \n"
        "  doi       = {10.1145/1833351.1778856}, \n"
        "  timestamp = {Wed, 27 May 2015 19:02:37 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/LevyL10}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/gmp/YanWLL10, \n"
        "  author    = {Dong{-}Ming Yan and \n"
        "               Wenping Wang and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Yang Liu}, \n"
        "  title     = {Efficient Computation of 3D Clipped Voronoi Diagram}, \n"
        "  booktitle = {Advances in Geometric Modeling and Processing, 6th International Conference, \n"
        "               {GMP} 2010, Castro Urdiales, Spain, June 16-18, 2010. Proceedings}, \n"
        "  pages     = {269--282}, \n"
        "  year      = {2010}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-642-13411-1_18}, \n"
        "  doi       = {10.1007/978-3-642-13411-1_18}, \n"
        "  timestamp = {Tue, 09 Sep 2014 19:02:15 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/gmp/YanWLL10}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cad/YanWLL13, \n"
        "  author    = {Dong{-}Ming Yan and \n"
        "               Wenping Wang and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Yang Liu}, \n"
        "  title     = {Efficient computation of clipped Voronoi diagram for mesh generation}, \n"
        "  journal   = {Computer-Aided Design}, \n"
        "  volume    = {45}, \n"
        "  number    = {4}, \n"
        "  pages     = {843--852}, \n"
        "  year      = {2013}, \n"
        "  url       = {http://dx.doi.org/10.1016/j.cad.2011.09.004}, \n"
        "  doi       = {10.1016/j.cad.2011.09.004}, \n"
        "  timestamp = {Tue, 09 Sep 2014 19:02:15 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cad/YanWLL13}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cad/Levy16, \n"
        "  author    = {Bruno L{\\'{e}}vy}, \n"
        "  title     = {Robustness and efficiency of geometric programs: The Predicate Construction \n"
        "               Kit {(PCK)}}, \n"
        "  journal   = {Computer-Aided Design}, \n"
        "  volume    = {72}, \n"
        "  pages     = {3--12}, \n"
        "  year      = {2016}, \n"
        "  url       = {http://dx.doi.org/10.1016/j.cad.2015.10.004}, \n"
        "  doi       = {10.1016/j.cad.2015.10.004}, \n"
        "  timestamp = {Tue, 16 Feb 2016 16:08:12 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cad/Levy16}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/RaySL16, \n"
        "  author    = {Nicolas Ray and \n"
        "               Dmitry Sokolov and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Practical 3D frame field generation}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {35}, \n"
        "  number    = {6}, \n"
        "  pages     = {233:1--233:9}, \n"
        "  year      = {2016}, \n"
        "  url       = {http://dl.acm.org/citation.cfm?id=2982408}, \n"
        "  timestamp = {Tue, 03 Jan 2017 12:35:33 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/RaySL16}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/SokolovRUL16, \n"
        "  author    = {Dmitry Sokolov and \n"
        "               Nicolas Ray and \n"
        "               Lionel Untereiner and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Hexahedral-Dominant Meshing}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {35}, \n"
        "  number    = {5}, \n"
        "  pages     = {157:1--157:23}, \n"
        "  year      = {2016}, \n"
        "  url       = {http://doi.acm.org/10.1145/2930662}, \n"
        "  doi       = {10.1145/2930662}, \n"
        "  timestamp = {Tue, 03 Jan 2017 12:35:33 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/SokolovRUL16}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@ARTICLE{Lloyd82leastsquares, \n"
        "    author = {Stuart P. Lloyd}, \n"
        "    title = {Least squares quantization in pcm}, \n"
        "    journal = {IEEE Transactions on Information Theory}, \n"
        "    year = {1982}, \n"
        "    volume = {28}, \n"
        "    pages = {129--137} \n"
        "} \n"
        " \n"
        "@article{Du:1999:CVT:340312.340319, \n"
        " author = {Du, Qiang and Faber, Vance and Gunzburger, Max}, \n"
        " title = {Centroidal Voronoi Tessellations: Applications and Algorithms}, \n"
        " journal = {SIAM Rev.}, \n"
        " issue_date = {Dec. 1999}, \n"
        " volume = {41}, \n"
        " number = {4}, \n"
        " month = dec, \n"
        " year = {1999}, \n"
        " issn = {0036-1445}, \n"
        " pages = {637--676}, \n"
        " numpages = {40}, \n"
        " url = {http://dx.doi.org/10.1137/S0036144599352836}, \n"
        " doi = {10.1137/S0036144599352836}, \n"
        " acmid = {340319}, \n"
        " publisher = {Society for Industrial and Applied Mathematics}, \n"
        " address = {Philadelphia, PA, USA}, \n"
        " keywords = {Voronoi tessellations, centroids, clustering, data compression, vector quantization}, \n"
        "} \n"
        " \n"
        " \n"
        "@inproceedings{DBLP:conf/compgeom/AurenhammerHA92, \n"
        "  author    = {Franz Aurenhammer and \n"
        "               Friedrich Hoffmann and \n"
        "               Boris Aronov}, \n"
        "  title     = {Minkowski-Type Theorems and Least-Squares Partitioning}, \n"
        "  booktitle = {Symposium on Computational Geometry}, \n"
        "  year      = {1992}, \n"
        "  pages     = {350-357}, \n"
        "  ee        = {http://doi.acm.org/10.1145/142675.142747}, \n"
        "  bibsource = {DBLP, http://dblp.uni-trier.de} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cgf/Merigot11, \n"
        "  author    = {Quentin M{\\'e}rigot}, \n"
        "  title     = {A Multiscale Approach to Optimal Transport}, \n"
        "  journal   = {Comput. Graph. Forum}, \n"
        "  volume    = {30}, \n"
        "  number    = {5}, \n"
        "  year      = {2011}, \n"
        "  pages     = {1583-1592}, \n"
        "  ee        = {http://dx.doi.org/10.1111/j.1467-8659.2011.02032.x}, \n"
        "  bibsource = {DBLP, http://dblp.uni-trier.de} \n"
        "} \n"
        " \n"
        "@article{journals/M2AN/LevyNAL15, \n"
        "   author  = {Bruno L{\\'{e}}vy}, \n"
        "   title   = {A Numerical Algorithm for {$L_2$} Semi-Discrete Optimal Transport in 3D}, \n"
        "   journal = {ESAIM M2AN (Mathematical Modeling and Analysis)}, \n"
        "   year    = 2015 \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/tog/LuftCD06, \n"
        "  author    = {Thomas Luft and \n"
        "               Carsten Colditz and \n"
        "               Oliver Deussen}, \n"
        "  title     = {Image enhancement by unsharp masking the depth buffer}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {25}, \n"
        "  number    = {3}, \n"
        "  pages     = {1206--1213}, \n"
        "  year      = {2006}, \n"
        "  url       = {http://doi.acm.org/10.1145/1141911.1142016}, \n"
        "  doi       = {10.1145/1141911.1142016}, \n"
        "  timestamp = {Tue, 22 Aug 2006 09:16:23 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/LuftCD06}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/corr/MerigotMT17, \n"
        "  author    = {Quentin M{\\'{e}}rigot and \n"
        "               Jocelyn Meyron and \n"
        "               Boris Thibert}, \n"
        "  title     = {An algorithm for optimal transport between a simplex soup and a point \n"
        "               cloud}, \n"
        "  journal   = {CoRR}, \n"
        "  volume    = {abs/1707.01337}, \n"
        "  year      = {2017}, \n"
        "  url       = {http://arxiv.org/abs/1707.01337}, \n"
        "  archivePrefix = {arXiv}, \n"
        "  eprint    = {1707.01337}, \n"
        "  timestamp = {Sat, 05 Aug 2017 14:56:07 +0200}, \n"
        "  biburl    = {https://dblp.org/rec/bib/journals/corr/MerigotMT17}, \n"
        "  bibsource = {dblp computer science bibliography, https://dblp.org} \n"
        "} \n"
     );

}
