var annotated_dup =
[
    [ "GEO", "namespaceGEO.html", [
      [ "FileSystem", "namespaceGEO_1_1FileSystem.html", [
        [ "MemoryNode", "classGEO_1_1FileSystem_1_1MemoryNode.html", "classGEO_1_1FileSystem_1_1MemoryNode" ],
        [ "Node", "classGEO_1_1FileSystem_1_1Node.html", "classGEO_1_1FileSystem_1_1Node" ]
      ] ],
      [ "GLSL", null, [
        [ "GLSLCompileError", "structGEO_1_1GLSL_1_1GLSLCompileError.html", "structGEO_1_1GLSL_1_1GLSLCompileError" ],
        [ "PseudoFileProvider", "classGEO_1_1GLSL_1_1PseudoFileProvider.html", "classGEO_1_1GLSL_1_1PseudoFileProvider" ],
        [ "Source", "classGEO_1_1GLSL_1_1Source.html", "classGEO_1_1GLSL_1_1Source" ]
      ] ],
      [ "Memory", "namespaceGEO_1_1Memory.html", [
        [ "aligned_allocator", "classGEO_1_1Memory_1_1aligned__allocator.html", "classGEO_1_1Memory_1_1aligned__allocator" ],
        [ "PointAlignment", "structGEO_1_1Memory_1_1PointAlignment.html", null ],
        [ "PointAlignment< 2 >", "structGEO_1_1Memory_1_1PointAlignment_3_012_01_4.html", null ],
        [ "PointAlignment< 3 >", "structGEO_1_1Memory_1_1PointAlignment_3_013_01_4.html", null ],
        [ "PointAlignment< 4 >", "structGEO_1_1Memory_1_1PointAlignment_3_014_01_4.html", null ],
        [ "PointAlignment< 6 >", "structGEO_1_1Memory_1_1PointAlignment_3_016_01_4.html", null ],
        [ "PointAlignment< 8 >", "structGEO_1_1Memory_1_1PointAlignment_3_018_01_4.html", null ]
      ] ],
      [ "Numeric", "namespaceGEO_1_1Numeric.html", [
        [ "Limits", "structGEO_1_1Numeric_1_1Limits.html", null ],
        [ "LimitsHelper", "structGEO_1_1Numeric_1_1LimitsHelper.html", null ],
        [ "LimitsHelper< T, true >", "structGEO_1_1Numeric_1_1LimitsHelper_3_01T_00_01true_01_4.html", null ]
      ] ],
      [ "PCK", "namespaceGEO_1_1PCK.html", [
        [ "PredicateStats", "classGEO_1_1PCK_1_1PredicateStats.html", null ]
      ] ],
      [ "Process", "namespaceGEO_1_1Process.html", [
        [ "BasicSpinLockArray", "classGEO_1_1Process_1_1BasicSpinLockArray.html", "classGEO_1_1Process_1_1BasicSpinLockArray" ]
      ] ],
      [ "String", null, [
        [ "ConversionError", "classGEO_1_1String_1_1ConversionError.html", "classGEO_1_1String_1_1ConversionError" ]
      ] ],
      [ "AABB", "classGEO_1_1AABB.html", "classGEO_1_1AABB" ],
      [ "AbstractCSGBuilder", "classGEO_1_1AbstractCSGBuilder.html", "classGEO_1_1AbstractCSGBuilder" ],
      [ "AdaptiveKdTree", "classGEO_1_1AdaptiveKdTree.html", "classGEO_1_1AdaptiveKdTree" ],
      [ "AmbientOcclusionImpl", "classGEO_1_1AmbientOcclusionImpl.html", "classGEO_1_1AmbientOcclusionImpl" ],
      [ "Application", "classGEO_1_1Application.html", "classGEO_1_1Application" ],
      [ "ArcBall", "classGEO_1_1ArcBall.html", "classGEO_1_1ArcBall" ],
      [ "Attribute", "classGEO_1_1Attribute.html", "classGEO_1_1Attribute" ],
      [ "Attribute< bool >", "classGEO_1_1Attribute_3_01bool_01_4.html", "classGEO_1_1Attribute_3_01bool_01_4" ],
      [ "Attribute< vecng< DIM, double > >", "classGEO_1_1Attribute_3_01vecng_3_01DIM_00_01double_01_4_01_4.html", "classGEO_1_1Attribute_3_01vecng_3_01DIM_00_01double_01_4_01_4" ],
      [ "AttributeBase", "classGEO_1_1AttributeBase.html", "classGEO_1_1AttributeBase" ],
      [ "AttributesManager", "classGEO_1_1AttributesManager.html", "classGEO_1_1AttributesManager" ],
      [ "AttributeStore", "classGEO_1_1AttributeStore.html", "classGEO_1_1AttributeStore" ],
      [ "AttributeStoreCreator", "classGEO_1_1AttributeStoreCreator.html", "classGEO_1_1AttributeStoreCreator" ],
      [ "AttributeStoreObserver", "classGEO_1_1AttributeStoreObserver.html", "classGEO_1_1AttributeStoreObserver" ],
      [ "AxisPermutation", "structGEO_1_1AxisPermutation.html", null ],
      [ "BalancedKdTree", "classGEO_1_1BalancedKdTree.html", "classGEO_1_1BalancedKdTree" ],
      [ "basic_bindex", "structGEO_1_1basic__bindex.html", "structGEO_1_1basic__bindex" ],
      [ "basic_quadindex", "structGEO_1_1basic__quadindex.html", "structGEO_1_1basic__quadindex" ],
      [ "basic_trindex", "structGEO_1_1basic__trindex.html", "structGEO_1_1basic__trindex" ],
      [ "Basis3d", "structGEO_1_1Basis3d.html", null ],
      [ "BBox", "structGEO_1_1BBox.html", null ],
      [ "BBox1", "structGEO_1_1BBox1.html", null ],
      [ "BinaryInputStream", "classGEO_1_1BinaryInputStream.html", "classGEO_1_1BinaryInputStream" ],
      [ "BinaryOutputStream", "classGEO_1_1BinaryOutputStream.html", "classGEO_1_1BinaryOutputStream" ],
      [ "BinaryStream", "classGEO_1_1BinaryStream.html", "classGEO_1_1BinaryStream" ],
      [ "BooleanExpression", "classGEO_1_1BooleanExpression.html", "classGEO_1_1BooleanExpression" ],
      [ "Box", "classGEO_1_1Box.html", "classGEO_1_1Box" ],
      [ "Box2d", "classGEO_1_1Box2d.html", "classGEO_1_1Box2d" ],
      [ "BuildRVDMesh", "classGEO_1_1BuildRVDMesh.html", "classGEO_1_1BuildRVDMesh" ],
      [ "Cavity", "classGEO_1_1Cavity.html", "classGEO_1_1Cavity" ],
      [ "CDT2d", "classGEO_1_1CDT2d.html", "classGEO_1_1CDT2d" ],
      [ "CDTBase2d", "classGEO_1_1CDTBase2d.html", "classGEO_1_1CDTBase2d" ],
      [ "CellDescriptor", "structGEO_1_1CellDescriptor.html", "structGEO_1_1CellDescriptor" ],
      [ "CellStatusArray", "classGEO_1_1CellStatusArray.html", "classGEO_1_1CellStatusArray" ],
      [ "CentroidalVoronoiTesselation", "classGEO_1_1CentroidalVoronoiTesselation.html", "classGEO_1_1CentroidalVoronoiTesselation" ],
      [ "Coeff", "structGEO_1_1Coeff.html", null ],
      [ "Colormap", "classGEO_1_1Colormap.html", "classGEO_1_1Colormap" ],
      [ "Command", "classGEO_1_1Command.html", "classGEO_1_1Command" ],
      [ "CommandInvoker", "classGEO_1_1CommandInvoker.html", "classGEO_1_1CommandInvoker" ],
      [ "Console", "classGEO_1_1Console.html", "classGEO_1_1Console" ],
      [ "ConsoleLogger", "classGEO_1_1ConsoleLogger.html", "classGEO_1_1ConsoleLogger" ],
      [ "const_index_ptr_in_array", "classGEO_1_1const__index__ptr__in__array.html", null ],
      [ "const_index_ptr_range", "classGEO_1_1const__index__ptr__range.html", null ],
      [ "CoplanarFacets", "classGEO_1_1CoplanarFacets.html", "classGEO_1_1CoplanarFacets" ],
      [ "CoTan3D", "structGEO_1_1CoTan3D.html", null ],
      [ "Counted", "classGEO_1_1Counted.html", "classGEO_1_1Counted" ],
      [ "CSGBuilder", "classGEO_1_1CSGBuilder.html", "classGEO_1_1CSGBuilder" ],
      [ "CSGCompiler", "classGEO_1_1CSGCompiler.html", "classGEO_1_1CSGCompiler" ],
      [ "DebugStream", "classGEO_1_1DebugStream.html", "classGEO_1_1DebugStream" ],
      [ "Delaunay", "classGEO_1_1Delaunay.html", "classGEO_1_1Delaunay" ],
      [ "Delaunay2d", "classGEO_1_1Delaunay2d.html", "classGEO_1_1Delaunay2d" ],
      [ "Delaunay3d", "classGEO_1_1Delaunay3d.html", "classGEO_1_1Delaunay3d" ],
      [ "Delaunay_NearestNeighbors", "classGEO_1_1Delaunay__NearestNeighbors.html", "classGEO_1_1Delaunay__NearestNeighbors" ],
      [ "DynamicHBoxes", "structGEO_1_1DynamicHBoxes.html", null ],
      [ "Environment", "classGEO_1_1Environment.html", "classGEO_1_1Environment" ],
      [ "ExactCDT2d", "classGEO_1_1ExactCDT2d.html", "classGEO_1_1ExactCDT2d" ],
      [ "expansion", "classGEO_1_1expansion.html", "classGEO_1_1expansion" ],
      [ "expansion_nt", "classGEO_1_1expansion__nt.html", "classGEO_1_1expansion__nt" ],
      [ "FacetIntersect", "structGEO_1_1FacetIntersect.html", null ],
      [ "FacetsExtraConnectivity", "structGEO_1_1FacetsExtraConnectivity.html", null ],
      [ "FacetsExtraConnectivityWithInvalidFacets", "structGEO_1_1FacetsExtraConnectivityWithInvalidFacets.html", null ],
      [ "Factory", "classGEO_1_1Factory.html", "classGEO_1_1Factory" ],
      [ "Factory0", "classGEO_1_1Factory0.html", null ],
      [ "Factory1", "classGEO_1_1Factory1.html", null ],
      [ "FactoryCreator0", "structGEO_1_1FactoryCreator0.html", "structGEO_1_1FactoryCreator0" ],
      [ "FactoryCreator1", "structGEO_1_1FactoryCreator1.html", "structGEO_1_1FactoryCreator1" ],
      [ "FF_param", "structGEO_1_1FF__param.html", null ],
      [ "FFopt", "classGEO_1_1FFopt.html", "classGEO_1_1FFopt" ],
      [ "FileLogger", "classGEO_1_1FileLogger.html", "classGEO_1_1FileLogger" ],
      [ "Frame", "structGEO_1_1Frame.html", null ],
      [ "FrameBufferObject", "classGEO_1_1FrameBufferObject.html", "classGEO_1_1FrameBufferObject" ],
      [ "FrameField", "classGEO_1_1FrameField.html", "classGEO_1_1FrameField" ],
      [ "FullScreenEffectImpl", "classGEO_1_1FullScreenEffectImpl.html", "classGEO_1_1FullScreenEffectImpl" ],
      [ "FunctionCommandInvoker", "classGEO_1_1FunctionCommandInvoker.html", "classGEO_1_1FunctionCommandInvoker" ],
      [ "GenColor", "classGEO_1_1GenColor.html", "classGEO_1_1GenColor" ],
      [ "GenericLifeCycle", "classGEO_1_1GenericLifeCycle.html", "classGEO_1_1GenericLifeCycle" ],
      [ "geo_declare_image_serializer", "classGEO_1_1geo__declare__image__serializer.html", "classGEO_1_1geo__declare__image__serializer" ],
      [ "geo_register_attribute_type", "classGEO_1_1geo__register__attribute__type.html", "classGEO_1_1geo__register__attribute__type" ],
      [ "GeoFile", "classGEO_1_1GeoFile.html", "classGEO_1_1GeoFile" ],
      [ "GeoFileException", "classGEO_1_1GeoFileException.html", "classGEO_1_1GeoFileException" ],
      [ "HBoxes", "structGEO_1_1HBoxes.html", null ],
      [ "HexdomParam", "structGEO_1_1HexdomParam.html", null ],
      [ "IdPair", "structGEO_1_1IdPair.html", null ],
      [ "Image", "classGEO_1_1Image.html", "classGEO_1_1Image" ],
      [ "ImageLibrary", "classGEO_1_1ImageLibrary.html", "classGEO_1_1ImageLibrary" ],
      [ "ImageRasterizer", "classGEO_1_1ImageRasterizer.html", "classGEO_1_1ImageRasterizer" ],
      [ "ImageSerializer", "classGEO_1_1ImageSerializer.html", "classGEO_1_1ImageSerializer" ],
      [ "ImageSerializer_pgm", "classGEO_1_1ImageSerializer__pgm.html", "classGEO_1_1ImageSerializer__pgm" ],
      [ "ImageSerializer_xpm", "classGEO_1_1ImageSerializer__xpm.html", "classGEO_1_1ImageSerializer__xpm" ],
      [ "ImageSerializerSTB", "classGEO_1_1ImageSerializerSTB.html", "classGEO_1_1ImageSerializerSTB" ],
      [ "ImageSerializerSTBRead", "classGEO_1_1ImageSerializerSTBRead.html", "classGEO_1_1ImageSerializerSTBRead" ],
      [ "ImageSerializerSTBReadWrite", "classGEO_1_1ImageSerializerSTBReadWrite.html", "classGEO_1_1ImageSerializerSTBReadWrite" ],
      [ "index_as_iterator", "classGEO_1_1index__as__iterator.html", null ],
      [ "index_ptr_in_array", "classGEO_1_1index__ptr__in__array.html", null ],
      [ "index_ptr_range", "classGEO_1_1index__ptr__range.html", null ],
      [ "index_range", "classGEO_1_1index__range.html", "classGEO_1_1index__range" ],
      [ "InputGeoFile", "classGEO_1_1InputGeoFile.html", "classGEO_1_1InputGeoFile" ],
      [ "InstanceRepo", "classGEO_1_1InstanceRepo.html", "classGEO_1_1InstanceRepo" ],
      [ "IntegrationSimplex", "classGEO_1_1IntegrationSimplex.html", "classGEO_1_1IntegrationSimplex" ],
      [ "intervalBase", "classGEO_1_1intervalBase.html", null ],
      [ "intervalRN", "classGEO_1_1intervalRN.html", "classGEO_1_1intervalRN" ],
      [ "intervalRU", "classGEO_1_1intervalRU.html", "classGEO_1_1intervalRU" ],
      [ "IsectInfo", "structGEO_1_1IsectInfo.html", "structGEO_1_1IsectInfo" ],
      [ "KdTree", "classGEO_1_1KdTree.html", "classGEO_1_1KdTree" ],
      [ "LifeCycle", "classGEO_1_1LifeCycle.html", "classGEO_1_1LifeCycle" ],
      [ "LinearLeastSquares", "classGEO_1_1LinearLeastSquares.html", "classGEO_1_1LinearLeastSquares" ],
      [ "LineInput", "classGEO_1_1LineInput.html", "classGEO_1_1LineInput" ],
      [ "LocalFeatureSize", "classGEO_1_1LocalFeatureSize.html", "classGEO_1_1LocalFeatureSize" ],
      [ "Logger", "classGEO_1_1Logger.html", "classGEO_1_1Logger" ],
      [ "LoggerClient", "classGEO_1_1LoggerClient.html", "classGEO_1_1LoggerClient" ],
      [ "LoggerStream", "classGEO_1_1LoggerStream.html", "classGEO_1_1LoggerStream" ],
      [ "LoggerStreamBuf", "classGEO_1_1LoggerStreamBuf.html", "classGEO_1_1LoggerStreamBuf" ],
      [ "lua_to", "classGEO_1_1lua__to.html", "classGEO_1_1lua__to" ],
      [ "lua_to< bool >", "classGEO_1_1lua__to_3_01bool_01_4.html", null ],
      [ "lua_to< const char * >", "classGEO_1_1lua__to_3_01const_01char_01_5_01_4.html", null ],
      [ "lua_to< const std::string & >", "classGEO_1_1lua__to_3_01const_01std_1_1string_01_6_01_4.html", null ],
      [ "lua_to< double >", "classGEO_1_1lua__to_3_01double_01_4.html", null ],
      [ "lua_to< float >", "classGEO_1_1lua__to_3_01float_01_4.html", null ],
      [ "lua_to< int >", "classGEO_1_1lua__to_3_01int_01_4.html", null ],
      [ "lua_to< Numeric::int64 >", "classGEO_1_1lua__to_3_01Numeric_1_1int64_01_4.html", null ],
      [ "lua_to< Numeric::uint32 >", "classGEO_1_1lua__to_3_01Numeric_1_1uint32_01_4.html", null ],
      [ "lua_to< Numeric::uint64 >", "classGEO_1_1lua__to_3_01Numeric_1_1uint64_01_4.html", null ],
      [ "lua_to< std::string >", "classGEO_1_1lua__to_3_01std_1_1string_01_4.html", null ],
      [ "lua_wrapper", "classGEO_1_1lua__wrapper.html", null ],
      [ "Matrix", "classGEO_1_1Matrix.html", "classGEO_1_1Matrix" ],
      [ "MatrixM", "structGEO_1_1MatrixM.html", null ],
      [ "MatrixMixedConstrainedSolver", "structGEO_1_1MatrixMixedConstrainedSolver.html", "structGEO_1_1MatrixMixedConstrainedSolver" ],
      [ "MemberFunctionCommandInvoker", "classGEO_1_1MemberFunctionCommandInvoker.html", "classGEO_1_1MemberFunctionCommandInvoker" ],
      [ "Mesh", "classGEO_1_1Mesh.html", "classGEO_1_1Mesh" ],
      [ "MeshAABB2d", "classGEO_1_1MeshAABB2d.html", "classGEO_1_1MeshAABB2d" ],
      [ "MeshAABB3d", "classGEO_1_1MeshAABB3d.html", "classGEO_1_1MeshAABB3d" ],
      [ "MeshCellCornersStore", "classGEO_1_1MeshCellCornersStore.html", "classGEO_1_1MeshCellCornersStore" ],
      [ "MeshCellFacetsStore", "classGEO_1_1MeshCellFacetsStore.html", "classGEO_1_1MeshCellFacetsStore" ],
      [ "MeshCells", "classGEO_1_1MeshCells.html", "classGEO_1_1MeshCells" ],
      [ "MeshCellsAABB", "classGEO_1_1MeshCellsAABB.html", "classGEO_1_1MeshCellsAABB" ],
      [ "MeshCellsStore", "classGEO_1_1MeshCellsStore.html", "classGEO_1_1MeshCellsStore" ],
      [ "MeshEdges", "classGEO_1_1MeshEdges.html", "classGEO_1_1MeshEdges" ],
      [ "MeshElements", "classGEO_1_1MeshElements.html", "classGEO_1_1MeshElements" ],
      [ "MeshFacetCornersStore", "classGEO_1_1MeshFacetCornersStore.html", "classGEO_1_1MeshFacetCornersStore" ],
      [ "MeshFacets", "classGEO_1_1MeshFacets.html", "classGEO_1_1MeshFacets" ],
      [ "MeshFacetsAABB", "classGEO_1_1MeshFacetsAABB.html", "classGEO_1_1MeshFacetsAABB" ],
      [ "MeshFacetsAABB2d", "classGEO_1_1MeshFacetsAABB2d.html", "classGEO_1_1MeshFacetsAABB2d" ],
      [ "MeshFacetsStore", "classGEO_1_1MeshFacetsStore.html", "classGEO_1_1MeshFacetsStore" ],
      [ "MeshGfx", "classGEO_1_1MeshGfx.html", "classGEO_1_1MeshGfx" ],
      [ "MeshHalfedges", "classGEO_1_1MeshHalfedges.html", "classGEO_1_1MeshHalfedges" ],
      [ "MeshInTriangle", "classGEO_1_1MeshInTriangle.html", "classGEO_1_1MeshInTriangle" ],
      [ "MeshIOFlags", "classGEO_1_1MeshIOFlags.html", "classGEO_1_1MeshIOFlags" ],
      [ "MeshIOHandler", "classGEO_1_1MeshIOHandler.html", "classGEO_1_1MeshIOHandler" ],
      [ "MeshSplitCallbacks", "classGEO_1_1MeshSplitCallbacks.html", "classGEO_1_1MeshSplitCallbacks" ],
      [ "MeshSubElementsStore", "classGEO_1_1MeshSubElementsStore.html", "classGEO_1_1MeshSubElementsStore" ],
      [ "MeshSurfaceIntersection", "classGEO_1_1MeshSurfaceIntersection.html", "classGEO_1_1MeshSurfaceIntersection" ],
      [ "MeshTetrahedralizeParameters", "structGEO_1_1MeshTetrahedralizeParameters.html", "structGEO_1_1MeshTetrahedralizeParameters" ],
      [ "MeshVertices", "classGEO_1_1MeshVertices.html", "classGEO_1_1MeshVertices" ],
      [ "MonoThreadingThreadManager", "classGEO_1_1MonoThreadingThreadManager.html", "classGEO_1_1MonoThreadingThreadManager" ],
      [ "MorphoMath", "classGEO_1_1MorphoMath.html", "classGEO_1_1MorphoMath" ],
      [ "NaiveSparseMatrix", "structGEO_1_1NaiveSparseMatrix.html", null ],
      [ "NearestNeighborSearch", "classGEO_1_1NearestNeighborSearch.html", "classGEO_1_1NearestNeighborSearch" ],
      [ "OptimalTransportMap", "classGEO_1_1OptimalTransportMap.html", "classGEO_1_1OptimalTransportMap" ],
      [ "OptimalTransportMap2d", "classGEO_1_1OptimalTransportMap2d.html", "classGEO_1_1OptimalTransportMap2d" ],
      [ "OptimalTransportMap3d", "classGEO_1_1OptimalTransportMap3d.html", "classGEO_1_1OptimalTransportMap3d" ],
      [ "OptimalTransportMapOnSurface", "classGEO_1_1OptimalTransportMapOnSurface.html", "classGEO_1_1OptimalTransportMapOnSurface" ],
      [ "Optimizer", "classGEO_1_1Optimizer.html", "classGEO_1_1Optimizer" ],
      [ "OutputGeoFile", "classGEO_1_1OutputGeoFile.html", "classGEO_1_1OutputGeoFile" ],
      [ "PackedArrays", "classGEO_1_1PackedArrays.html", "classGEO_1_1PackedArrays" ],
      [ "ParallelDelaunay3d", "classGEO_1_1ParallelDelaunay3d.html", "classGEO_1_1ParallelDelaunay3d" ],
      [ "ParamValidator", "classGEO_1_1ParamValidator.html", "classGEO_1_1ParamValidator" ],
      [ "Periodic", "classGEO_1_1Periodic.html", "classGEO_1_1Periodic" ],
      [ "PeriodicDelaunay3d", "classGEO_1_1PeriodicDelaunay3d.html", "classGEO_1_1PeriodicDelaunay3d" ],
      [ "PGPopt", "classGEO_1_1PGPopt.html", null ],
      [ "Plane", "structGEO_1_1Plane.html", "structGEO_1_1Plane" ],
      [ "Poly2d", "structGEO_1_1Poly2d.html", null ],
      [ "Poly3d", "structGEO_1_1Poly3d.html", "structGEO_1_1Poly3d" ],
      [ "PrincipalAxes3d", "classGEO_1_1PrincipalAxes3d.html", "classGEO_1_1PrincipalAxes3d" ],
      [ "ProgressClient", "classGEO_1_1ProgressClient.html", "classGEO_1_1ProgressClient" ],
      [ "ProgressTask", "classGEO_1_1ProgressTask.html", "classGEO_1_1ProgressTask" ],
      [ "Quaternion", "classGEO_1_1Quaternion.html", "classGEO_1_1Quaternion" ],
      [ "rationalg", "classGEO_1_1rationalg.html", "classGEO_1_1rationalg" ],
      [ "Ray", "structGEO_1_1Ray.html", "structGEO_1_1Ray" ],
      [ "ReadOnlyScalarAttributeAdapter", "classGEO_1_1ReadOnlyScalarAttributeAdapter.html", "classGEO_1_1ReadOnlyScalarAttributeAdapter" ],
      [ "ReadWriteScalarAttributeAdapter", "classGEO_1_1ReadWriteScalarAttributeAdapter.html", null ],
      [ "RegularWeightedDelaunay2d", "classGEO_1_1RegularWeightedDelaunay2d.html", "classGEO_1_1RegularWeightedDelaunay2d" ],
      [ "RegularWeightedDelaunay3d", "classGEO_1_1RegularWeightedDelaunay3d.html", "classGEO_1_1RegularWeightedDelaunay3d" ],
      [ "RemoveColMatrix", "structGEO_1_1RemoveColMatrix.html", null ],
      [ "RestrictedVoronoiDiagram", "classGEO_1_1RestrictedVoronoiDiagram.html", "classGEO_1_1RestrictedVoronoiDiagram" ],
      [ "RVDCallback", "classGEO_1_1RVDCallback.html", "classGEO_1_1RVDCallback" ],
      [ "RVDMeshBuilder", "classGEO_1_1RVDMeshBuilder.html", "classGEO_1_1RVDMeshBuilder" ],
      [ "RVDPolygonCallback", "classGEO_1_1RVDPolygonCallback.html", "classGEO_1_1RVDPolygonCallback" ],
      [ "RVDPolyhedronCallback", "classGEO_1_1RVDPolyhedronCallback.html", "classGEO_1_1RVDPolyhedronCallback" ],
      [ "RVDVertexMap", "classGEO_1_1RVDVertexMap.html", "classGEO_1_1RVDVertexMap" ],
      [ "ScalarAttributeAdapterBase", "classGEO_1_1ScalarAttributeAdapterBase.html", "classGEO_1_1ScalarAttributeAdapterBase" ],
      [ "SimpleApplication", "classGEO_1_1SimpleApplication.html", "classGEO_1_1SimpleApplication" ],
      [ "SimpleMeshApplication", "classGEO_1_1SimpleMeshApplication.html", "classGEO_1_1SimpleMeshApplication" ],
      [ "SmartPointer", "classGEO_1_1SmartPointer.html", "classGEO_1_1SmartPointer" ],
      [ "SphericalHarmonicL4", "structGEO_1_1SphericalHarmonicL4.html", null ],
      [ "StatusBar", "classGEO_1_1StatusBar.html", "classGEO_1_1StatusBar" ],
      [ "Stopwatch", "classGEO_1_1Stopwatch.html", "classGEO_1_1Stopwatch" ],
      [ "StructuringElement", "classGEO_1_1StructuringElement.html", "classGEO_1_1StructuringElement" ],
      [ "SystemEnvironment", "classGEO_1_1SystemEnvironment.html", "classGEO_1_1SystemEnvironment" ],
      [ "TaskCanceled", "structGEO_1_1TaskCanceled.html", "structGEO_1_1TaskCanceled" ],
      [ "TextEditor", "classGEO_1_1TextEditor.html", null ],
      [ "Thread", "classGEO_1_1Thread.html", "classGEO_1_1Thread" ],
      [ "ThreadManager", "classGEO_1_1ThreadManager.html", "classGEO_1_1ThreadManager" ],
      [ "transformed_iterator", "classGEO_1_1transformed__iterator.html", null ],
      [ "transformed_iterator_ref", "classGEO_1_1transformed__iterator__ref.html", null ],
      [ "transformed_range", "classGEO_1_1transformed__range.html", null ],
      [ "transformed_range_ref", "classGEO_1_1transformed__range__ref.html", null ],
      [ "TrFan", "structGEO_1_1TrFan.html", "structGEO_1_1TrFan" ],
      [ "TrglGradient", "classGEO_1_1TrglGradient.html", "classGEO_1_1TrglGradient" ],
      [ "TypedAttributeStore", "classGEO_1_1TypedAttributeStore.html", "classGEO_1_1TypedAttributeStore" ],
      [ "TypedAttributeStoreCreator", "classGEO_1_1TypedAttributeStoreCreator.html", "classGEO_1_1TypedAttributeStoreCreator" ],
      [ "TypedThreadGroup", "classGEO_1_1TypedThreadGroup.html", "classGEO_1_1TypedThreadGroup" ],
      [ "UncenteredPCA3D", "structGEO_1_1UncenteredPCA3D.html", null ],
      [ "UnsharpMaskingImpl", "classGEO_1_1UnsharpMaskingImpl.html", "classGEO_1_1UnsharpMaskingImpl" ],
      [ "VariableObserver", "classGEO_1_1VariableObserver.html", "classGEO_1_1VariableObserver" ],
      [ "VariableObserverList", "classGEO_1_1VariableObserverList.html", "classGEO_1_1VariableObserverList" ],
      [ "vec2Hg", "classGEO_1_1vec2Hg.html", "classGEO_1_1vec2Hg" ],
      [ "vec2HgLexicoCompare", "classGEO_1_1vec2HgLexicoCompare.html", "classGEO_1_1vec2HgLexicoCompare" ],
      [ "vec3Hg", "classGEO_1_1vec3Hg.html", "classGEO_1_1vec3Hg" ],
      [ "vec3HgLexicoCompare", "classGEO_1_1vec3HgLexicoCompare.html", "classGEO_1_1vec3HgLexicoCompare" ],
      [ "vecng", "classGEO_1_1vecng.html", "classGEO_1_1vecng" ],
      [ "vecng< 2, T >", "classGEO_1_1vecng_3_012_00_01T_01_4.html", "classGEO_1_1vecng_3_012_00_01T_01_4" ],
      [ "vecng< 3, T >", "classGEO_1_1vecng_3_013_00_01T_01_4.html", "classGEO_1_1vecng_3_013_00_01T_01_4" ],
      [ "vecng< 4, T >", "classGEO_1_1vecng_3_014_00_01T_01_4.html", "classGEO_1_1vecng_3_014_00_01T_01_4" ],
      [ "vector", "classGEO_1_1vector.html", "classGEO_1_1vector" ],
      [ "vector< bool >", "classGEO_1_1vector_3_01bool_01_4.html", "classGEO_1_1vector_3_01bool_01_4" ],
      [ "VSDM", "classGEO_1_1VSDM.html", "classGEO_1_1VSDM" ]
    ] ],
    [ "GEOCSG", null, [
      [ "ArgList", "classGEOCSG_1_1ArgList.html", null ],
      [ "Value", "structGEOCSG_1_1Value.html", null ]
    ] ],
    [ "GEOGen", null, [
      [ "ConvexCell", "classGEOGen_1_1ConvexCell.html", "classGEOGen_1_1ConvexCell" ],
      [ "FacetSeed", "structGEOGen_1_1FacetSeed.html", "structGEOGen_1_1FacetSeed" ],
      [ "FacetSeedMarking", "classGEOGen_1_1FacetSeedMarking.html", "classGEOGen_1_1FacetSeedMarking" ],
      [ "PointAllocator", "classGEOGen_1_1PointAllocator.html", "classGEOGen_1_1PointAllocator" ],
      [ "Polygon", "classGEOGen_1_1Polygon.html", "classGEOGen_1_1Polygon" ],
      [ "RestrictedVoronoiDiagram", "classGEOGen_1_1RestrictedVoronoiDiagram.html", "classGEOGen_1_1RestrictedVoronoiDiagram" ],
      [ "small_set", "classGEOGen_1_1small__set.html", "classGEOGen_1_1small__set" ],
      [ "SymbolicVertex", "classGEOGen_1_1SymbolicVertex.html", "classGEOGen_1_1SymbolicVertex" ],
      [ "VectorStack", "classGEOGen_1_1VectorStack.html", "classGEOGen_1_1VectorStack" ],
      [ "Vertex", "classGEOGen_1_1Vertex.html", "classGEOGen_1_1Vertex" ]
    ] ],
    [ "GLUP", null, [
      [ "Context", "classGLUP_1_1Context.html", "classGLUP_1_1Context" ],
      [ "FloatsArrayStateVariable", "classGLUP_1_1FloatsArrayStateVariable.html", "classGLUP_1_1FloatsArrayStateVariable" ],
      [ "ImmediateBuffer", "classGLUP_1_1ImmediateBuffer.html", "classGLUP_1_1ImmediateBuffer" ],
      [ "ImmediateState", "classGLUP_1_1ImmediateState.html", "classGLUP_1_1ImmediateState" ],
      [ "MarchingCell", "classGLUP_1_1MarchingCell.html", "classGLUP_1_1MarchingCell" ],
      [ "MatrixStack", "classGLUP_1_1MatrixStack.html", "classGLUP_1_1MatrixStack" ],
      [ "PrimitiveInfo", "structGLUP_1_1PrimitiveInfo.html", "structGLUP_1_1PrimitiveInfo" ],
      [ "StateVariable", "classGLUP_1_1StateVariable.html", "classGLUP_1_1StateVariable" ],
      [ "StateVariableBase", "classGLUP_1_1StateVariableBase.html", "classGLUP_1_1StateVariableBase" ],
      [ "UniformState", "structGLUP_1_1UniformState.html", null ],
      [ "VectorStateVariable", "classGLUP_1_1VectorStateVariable.html", "classGLUP_1_1VectorStateVariable" ]
    ] ],
    [ "VBW", null, [
      [ "ConvexCell", "classVBW_1_1ConvexCell.html", "classVBW_1_1ConvexCell" ],
      [ "Triangle", "structVBW_1_1Triangle.html", null ],
      [ "TriangleWithFlags", "structVBW_1_1TriangleWithFlags.html", null ]
    ] ],
    [ "LogTime", "structLogTime.html", "structLogTime" ],
    [ "Ray", "structRay.html", null ],
    [ "UniformState", "structUniformState.html", null ],
    [ "VSUniformState", "structVSUniformState.html", null ]
];