var dir_1b5ef1aaca6d6baabea834aee2fca889 =
[
    [ "basic.h", "basic_8h_source.html", null ],
    [ "cavity.h", "exploragram_2hexdom_2cavity_8h_source.html", null ],
    [ "extra_connectivity.h", "extra__connectivity_8h_source.html", null ],
    [ "FF.h", "FF_8h_source.html", null ],
    [ "FF_visu.h", "FF__visu_8h_source.html", null ],
    [ "frame.h", "frame_8h_source.html", null ],
    [ "geometry.h", "exploragram_2hexdom_2geometry_8h_source.html", null ],
    [ "hex.h", "hex_8h_source.html", null ],
    [ "hex_candidates.h", "hex__candidates_8h_source.html", null ],
    [ "hex_cruncher.h", "hex__cruncher_8h_source.html", null ],
    [ "hex_dominant.h", "hex__dominant_8h_source.html", null ],
    [ "hexdom_pipeline.h", "hexdom__pipeline_8h_source.html", null ],
    [ "id_map.h", "id__map_8h_source.html", null ],
    [ "intersect_tools.h", "intersect__tools_8h_source.html", null ],
    [ "mesh_inspector.h", "mesh__inspector_8h_source.html", null ],
    [ "mesh_utils.h", "mesh__utils_8h_source.html", null ],
    [ "meshcomesh.h", "meshcomesh_8h_source.html", null ],
    [ "mixed_constrained_solver.h", "mixed__constrained__solver_8h_source.html", null ],
    [ "PGP.h", "PGP_8h_source.html", null ],
    [ "polygon.h", "polygon_8h_source.html", null ],
    [ "preprocessing.h", "preprocessing_8h_source.html", null ],
    [ "quad_cover.h", "quad__cover_8h_source.html", null ],
    [ "quad_dominant.h", "quad__dominant_8h.html", "quad__dominant_8h" ],
    [ "quadmesher.h", "quadmesher_8h_source.html", null ],
    [ "quads_from_boundary.h", "quads__from__boundary_8h_source.html", null ],
    [ "sphere_model.h", "sphere__model_8h_source.html", null ],
    [ "spherical_harmonics_l4.h", "spherical__harmonics__l4_8h_source.html", null ],
    [ "time_log.h", "time__log_8h_source.html", null ]
];